// Property Order Rules Arranged from stylelint-config-recess-order
// GitHub: https://github.com/stormwarning/stylelint-config-recess-order
module.exports = {
    extends: ['stylelint-config-recommended-scss'],
    plugins: ['stylelint-order'],
    rules: {
      'font-family-no-duplicate-names': true,
      'function-calc-no-invalid': true,
      'function-calc-no-unspaced-operator': true,
      'string-no-newline': true,
      'unit-no-unknown': true,
      'property-no-unknown': true,
      'keyframe-declaration-no-important': true,
      'declaration-block-no-duplicate-properties': true,
      'block-no-empty': null,
      'selector-pseudo-class-no-unknown': true,
      'selector-pseudo-element-no-unknown': true,
      'selector-type-no-unknown': true,
      'scss/at-rule-no-unknown': [true, {
        ignoreAtRules: ['tailwind', 'apply', 'variants', 'responsive', 'screen', 'layer']
      }],
      'no-descending-specificity': null,
      'no-duplicate-at-import-rules': true,
      'no-duplicate-selectors': true,
      'no-extra-semicolons': true,
      'color-named': 'never',
      'keyframes-name-pattern': 'animate-.+',
      'declaration-block-single-line-max-declarations': 1,
      'selector-max-compound-selectors': 5,
      'selector-max-empty-lines': 0,
      'selector-pseudo-element-colon-notation': 'double',
      'max-nesting-depth': 5,
      'color-hex-case': 'lower',
      'function-comma-space-after': 'always',
      'function-comma-space-before': 'never',
      'function-max-empty-lines': 0,
      'function-name-case': 'lower',
      'function-url-quotes': 'always',
      'function-whitespace-after': 'always',
      'number-leading-zero': 'never',
      'number-no-trailing-zeros': true,
      'string-quotes': 'single',
      'unit-case': 'lower',
      'value-keyword-case': 'lower',
      'value-list-max-empty-lines': 0,
      'custom-property-empty-line-before': 'never',
      'property-case': 'lower',
      'declaration-bang-space-after': 'never',
      'declaration-bang-space-before': 'always',
      'declaration-colon-space-after': 'always',
      'declaration-colon-space-before': 'never',
      'declaration-empty-line-before': 'never',
      'declaration-block-semicolon-newline-after': 'always',
      'declaration-block-semicolon-space-before': 'never',
      'declaration-block-trailing-semicolon': 'always',
      'block-closing-brace-empty-line-before': 'never',
      'block-closing-brace-newline-before': 'always',
      'block-opening-brace-newline-after': 'always',
      'block-opening-brace-space-before': 'always',
      'selector-attribute-brackets-space-inside': 'never',
      'selector-attribute-operator-space-after': 'never',
      'selector-attribute-operator-space-before': 'never',
      'selector-attribute-quotes': 'always',
      'selector-combinator-space-after': 'always',
      'selector-combinator-space-before': 'always',
      'selector-descendant-combinator-no-non-space': true,
      'selector-pseudo-class-case': 'lower',
      'selector-pseudo-class-parentheses-space-inside': 'never',
      'selector-pseudo-element-case': 'lower',
      'selector-list-comma-newline-after': 'always',
      'selector-list-comma-space-before': 'never',
      'rule-empty-line-before': ['always-multi-line', {
        except: ['first-nested'],
        ignore: ['after-comment']
      }],
      'media-feature-colon-space-after': 'always',
      'media-feature-colon-space-before': 'never',
      'media-feature-name-case': 'lower',
      'media-feature-parentheses-space-inside': 'never',
      'media-feature-range-operator-space-after': 'always',
      'media-feature-range-operator-space-before': 'always',
      'media-query-list-comma-space-after': 'always',
      'media-query-list-comma-space-before': 'never',
      'at-rule-name-case': 'lower',
      'at-rule-name-space-after': 'always',
      'at-rule-semicolon-newline-after': 'always',
      'at-rule-semicolon-space-before': 'never',
      indentation: 2,
      'max-empty-lines': 1,
      'no-eol-whitespace': true,
      'order/properties-order': [
        {
            // Must be first.
            properties: ['all', 'content', 'appearance']
          },
          {
            // Position.
            properties: [
              'position',
              'top',
              'right',
              'bottom',
              'left',
              'z-index'
            ]
          },
          {
            // Display mode.
            properties: ['box-sizing', 'display']
          },
          {
            // Flexible boxes.
            properties: [
              'flex',
              'flex-basis',
              'flex-direction',
              'flex-flow',
              'flex-grow',
              'flex-shrink',
              'flex-wrap'
            ]
          },
          {
            // Grid layout.
            properties: [
              'grid',
              'grid-area',
              'grid-template',
              'grid-template-areas',
              'grid-template-rows',
              'grid-template-columns',
              'grid-row',
              'grid-row-start',
              'grid-row-end',
              'grid-column',
              'grid-column-start',
              'grid-column-end',
              'grid-auto-rows',
              'grid-auto-columns',
              'grid-auto-flow',
              'grid-gap',
              'grid-row-gap',
              'grid-column-gap'
            ]
          },
          {
            // Gap.
            properties: ['gap', 'row-gap', 'column-gap']
          },
          {
            // Layout alignment.
            properties: [
              'place-items',
              'align-content',
              'align-items',
              'align-self',
              'justify-content',
              'justify-items',
              'justify-self'
            ]
          },
          {
            // Order.
            properties: ['order']
          },
          {
            // Box model.
            properties: [
              'float',
              'width',
              'min-width',
              'max-width',
              'height',
              'min-height',
              'max-height',
              'margin',
              'margin-top',
              'margin-right',
              'margin-bottom',
              'margin-left',
              'padding',
              'padding-top',
              'padding-right',
              'padding-bottom',
              'padding-left',
              'overflow',
              'overflow-x',
              'overflow-y',
              '-webkit-overflow-scrolling',
              '-ms-overflow-x',
              '-ms-overflow-y',
              '-ms-overflow-style',
              'overscroll-behavior',
              'overscroll-behavior-x',
              'overscroll-behavior-y',
              'overscroll-behavior-inline',
              'overscroll-behavior-block',
              'clip',
              'clip-path',
              'clear'
            ]
          },
          {
            // Typography.
            properties: [
              'font',
              'font-family',
              'font-size',
              'font-style',
              'font-weight',
              'font-feature-settings',
              'font-kerning',
              'font-variant',
              'font-variant-ligatures',
              'font-variant-caps',
              'font-variant-alternates',
              'font-variant-numeric',
              'font-variant-east-asian',
              'font-variant-position',
              'font-size-adjust',
              'font-stretch',
              'font-effect',
              'font-emphasize',
              'font-emphasize-position',
              'font-emphasize-style',
              '-webkit-font-smoothing',
              '-moz-osx-font-smoothing',
              'font-smooth',
              'hyphens',
              'line-height',
              'color',
              'text-align',
              'text-align-last',
              'text-emphasis',
              'text-emphasis-color',
              'text-emphasis-style',
              'text-emphasis-position',
              'text-decoration',
              'text-decoration-line',
              'text-decoration-thickness',
              'text-decoration-style',
              'text-decoration-color',
              'text-underline-position',
              'text-underline-offset',
              'text-indent',
              'text-justify',
              'text-outline',
              '-ms-text-overflow',
              'text-overflow',
              'text-overflow-ellipsis',
              'text-overflow-mode',
              'text-shadow',
              'text-transform',
              'text-wrap',
              '-webkit-text-size-adjust',
              '-ms-text-size-adjust',
              'letter-spacing',
              'word-break',
              'word-spacing',
              'word-wrap', // Legacy name for `overflow-wrap`
              'overflow-wrap',
              'tab-size',
              'white-space',
              'vertical-align',
              'list-style',
              'list-style-position',
              'list-style-type',
              'list-style-image'
            ]
          },
          {
            // Accessibility & Interactions.
            properties: [
              'pointer-events',
              '-ms-touch-action',
              'touch-action',
              'cursor',
              'visibility',
              'zoom',
              'table-layout',
              'empty-cells',
              'caption-side',
              'border-spacing',
              'border-collapse',
              'quotes',
              'counter-reset',
              'counter-increment',
              'resize',
              'user-select',
              'nav-index',
              'nav-up',
              'nav-right',
              'nav-down',
              'nav-left'
            ]
          },
          {
            // Background & Borders.
            properties: [
              'background',
              'background-color',
              'background-image',
              "-ms-filter:\\'progid:DXImageTransform.Microsoft.gradient",
              'filter:progid:DXImageTransform.Microsoft.gradient',
              'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader',
              'filter',
              'background-repeat',
              'background-attachment',
              'background-position',
              'background-position-x',
              'background-position-y',
              'background-clip',
              'background-origin',
              'background-size',
              'background-blend-mode',
              'isolation',
              'border',
              'border-color',
              'border-style',
              'border-width',
              'border-top',
              'border-top-color',
              'border-top-style',
              'border-top-width',
              'border-right',
              'border-right-color',
              'border-right-style',
              'border-right-width',
              'border-bottom',
              'border-bottom-color',
              'border-bottom-style',
              'border-bottom-width',
              'border-left',
              'border-left-color',
              'border-left-style',
              'border-left-width',
              'border-radius',
              'border-top-left-radius',
              'border-top-right-radius',
              'border-bottom-right-radius',
              'border-bottom-left-radius',
              'border-image',
              'border-image-source',
              'border-image-slice',
              'border-image-width',
              'border-image-outset',
              'border-image-repeat',
              'outline',
              'outline-width',
              'outline-style',
              'outline-color',
              'outline-offset',
              'box-shadow',
              'mix-blend-mode',
              'filter:progid:DXImageTransform.Microsoft.Alpha(Opacity',
              "-ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha",
              'opacity',
              '-ms-interpolation-mode'
            ]
          },
          {
            // SVG Presentation Attributes.
            properties: [
              'alignment-baseline',
              'baseline-shift',
              'dominant-baseline',
              'text-anchor',
              'word-spacing',
              'writing-mode',
    
              'fill',
              'fill-opacity',
              'fill-rule',
              'stroke',
              'stroke-dasharray',
              'stroke-dashoffset',
              'stroke-linecap',
              'stroke-linejoin',
              'stroke-miterlimit',
              'stroke-opacity',
              'stroke-width',
    
              'color-interpolation',
              'color-interpolation-filters',
              'color-profile',
              'color-rendering',
              'flood-color',
              'flood-opacity',
              'image-rendering',
              'lighting-color',
              'marker-start',
              'marker-mid',
              'marker-end',
              'mask',
              'shape-rendering',
              'stop-color',
              'stop-opacity'
            ]
          },
          {
            // Transitions & Animation.
            properties: [
              'transition',
              'transition-delay',
              'transition-timing-function',
              'transition-duration',
              'transition-property',
              'transform',
              'transform-origin',
              'animation',
              'animation-name',
              'animation-duration',
              'animation-play-state',
              'animation-timing-function',
              'animation-delay',
              'animation-iteration-count',
              'animation-direction'
            ]
          }
      ]
    },
    ignoreFiles: ['.vscode/**', 'dist/**', 'node_modules/**']
  }